# Generated by Django 4.0.3 on 2022-03-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=40)),
                ('form', models.CharField(max_length=5)),
                ('logo', models.URLField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_schedule.league')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=40)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('injury', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='football_schedule.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=8)),
                ('goals_home', models.IntegerField(null=True)),
                ('goals_away', models.IntegerField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away', to='football_schedule.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home', to='football_schedule.team')),
            ],
        ),
    ]
