# Generated by Django 4.0.3 on 2022-03-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='odds_away',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='odds_home',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
